version: '2.1'

services:

  data:
    image: busybox
    volumes:
      - ./hello:/code

  webserver:
    extends:
      file: ./nginx/docker-compose.yml
      service: webserver
    volumes_from: [data]
    ports:
      - "8080:80"

  php:
    container_name: erdiko_php
    env_file: ./environment.env
    build:
      context: ./php
      dockerfile: Dockerfile
    image: erdiko/php-fpm:latest-xdebug-mac
    volumes_from: [data]

#  php:
#    container_name: erdiko_php
#    env_file: ./environment.env
#    image: erdiko/php-fpm:latest-xdebug
#    volumes_from: [data]
