version: '2.1'

services:
  node:
    env_file: environment.env
    image: erdiko_angular
    build:
      context: ./
    volumes:
      - ../../:/var/www/code
    entrypoint:
      - tail
      - -f
      - /dev/null
